// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateGif(arg1:main.GifConfig):Promise<string>;

export function GetImages(arg1:string):Promise<Array<main.ImageInfo>>;

export function GetProgress():Promise<number>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function SelectOutputFile():Promise<string>;
