// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateGif(arg1) {
  return window['go']['main']['App']['GenerateGif'](arg1);
}

export function GetImages(arg1) {
  return window['go']['main']['App']['GetImages'](arg1);
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectOutputFile() {
  return window['go']['main']['App']['SelectOutputFile']();
}
